pizza/urls.py
from django.urls import path
from . import views
#import views module from urls module

app_name = 'pizza'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizza',views.pizza,name='pizza'),
    path('pizza/<int:pizza_id>/',views.p,name='pizza'),
    path('new_comment/<int:pizza_id>/',views.new_comment,name='new_comment'),
]

pizza/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        #allows us to set a special attibute telling django to use toppings when referring to more than one
        verbose_name_plural = 'toppings'

    def __str__(self):
        return f"{self.text[:35]}..."

        
class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)      

    class Meta:
        #allows us to set a special attibute telling django to use toppings when referring to more than one
        verbose_name_plural = 'comments'

    def __str__(self):
        return f"{self.text[:35]}..."

pizza/forms.py
from django import forms
from .models import Pizza, Comment, Topping

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

pizza/views.py
from django.shortcuts import render, redirect
from .models import Pizza
from .forms import CommentForm
# Create your views here.

def index(request):
    """The Home Page for Pizza App"""
    return render(request, 'pizza/index.html')

def pizza(request):
    pizza = Pizza.objects.order_by('date_added')

    context = {'pizza':pizza}

    return render(request, 'pizza/pizza.html', context)

def p(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza':pizza, 'toppings':toppings}

    return render(request, 'pizza/p.html', context)

def new_comment(request,pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():

            new_comment = form.save(commit=False)

            new_comment.pizza = pizza
            new_comment.save()
            form.save()
        
            return redirect('pizza:pizza', pizza_id=pizza_id)

    context = {'form':form, 'pizza':pizza}
    return render(request, 'pizza/new_comment.html', context)

pizza/templates/pizza/base.html
<p>
    <a href="{% url 'pizza:index' %}">Home</a>
    <a href="{% url 'pizza:pizza' %}">Pizza</a>   
</p>



<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Django and Vue.js</title>
  </head>
  <body class="bg-light">
    <div class="bg-white container">

    </div>

    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/vue-router"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
{% block content %}{% endblock content %}

pizza/templates/pizza/index.html
{% extends "pizza/base.html" %}

{% block content %}


<h2>
<p>Pizza App</p>
<h4>


    
    {% load static %}

    <img src="{% static 'pizza/PizzaHut.jpg' %}" alt="Pizza">

<p>This app helps you see what pizza and toppings are available</p>
<h5>

{% endblock content %}

pizza/templates/pizza/new_comment.html
{% extends "pizza/base.html" %}

{% block content %}

  <p<a href="{% url 'pizza:pizza' pizza.id %}">{{ pizza }}</a></p>

  <p>Add a Comment:</p>

  <form action="{% url 'pizza:new_comment' pizza.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">Add Comment</button>
  </form>


{% endblock content %}

pizza/templates/pizza/p.html
{% extends "pizza/base.html" %}

{% block content %}

  <p>Pizza: {{ pizza }}</p>

  <ul>

    
    {% for topping in toppings %}

    <p>Topping: {{ topping.text }}</p>

    {% empty %}
    <li>No toppings have been added yet.</li>
    {% endfor %}

    {% for comment in comments %}

    <p>Comment: {{ comment.text }}</p>


    {% endfor %}

  </ul>

<p>
  <a href="{% url 'pizza:new_comment' pizza.id %}">Add New Comment</a>
</p>




{% endblock content %}

pizza/templates/pizza/pizza.html
{% extends "pizza/base.html" %}

{% block content %}

  <p>Pizzas</p>

  <ul>


    {% for pizza in pizza %}


    <li>
      <a href="{% url 'pizza:pizza' pizza.id %}">{{ pizza }}</a>
    </li>
    {% empty %}
    <li>No Pizzas have been added yet.</li>
    {% endfor %}



  </ul>







{% endblock content %}